export const blueprintSections = [
  { id: 's01', number: '01', title: 'Opportunity Brief', group: 'Market', icon: 'sparkles', height: '1550px' },
  { id: 's02', number: '02', title: 'Product Spec', group: 'Product', icon: 'file', height: '1850px' },
  { id: 's03', number: '03', title: 'Target Markets', group: 'Market', icon: 'compass', height: '1950px' },
  { id: 's04', number: '04', title: 'Tech Stack', group: 'Product', icon: 'layout', height: '1650px' },
  { id: 's05', number: '05', title: 'Competitor Map', group: 'Market', icon: 'chart', height: '1450px' },
  { id: 's06', number: '06', title: 'Revenue Model', group: 'Revenue', icon: 'chart', height: '1850px' },
  { id: 's07', number: '07', title: 'First 50 Customers', group: 'GTM', icon: 'book', height: '1700px' },
  { id: 's08', number: '08', title: 'Conversion Funnels', group: 'GTM', icon: 'compass', height: '1950px' },
  { id: 's09', number: '09', title: 'AI Build Prompts', group: 'AI / Build', icon: 'pencil', height: '4200px' },
  { id: 's10', number: '10', title: 'Design System', group: 'Product', icon: 'layout', height: '1600px' },
  { id: 's11', number: '11', title: 'UI Kit', group: 'Product', icon: 'layout', height: '2200px' },
  { id: 's12', number: '12', title: 'Prompt Pack', group: 'AI / Build', icon: 'pencil', height: '2200px' },
  { id: 's13', number: '13', title: 'API Schema', group: 'Product', icon: 'file', height: '2600px' },
  { id: 's14', number: '14', title: 'Database Schema', group: 'Product', icon: 'file', height: '3000px' },
  { id: 's15', number: '15', title: 'Landing Page Copy', group: 'Copy / Brand', icon: 'sparkles', height: '2600px' },
  { id: 's16', number: '16', title: 'Waitlist Emails', group: 'Copy / Brand', icon: 'book', height: '3000px' },
  { id: 's17', number: '17', title: 'Branding Kit', group: 'Copy / Brand', icon: 'layout', height: '2000px' },
  { id: 's18', number: '18', title: 'Launch Checklist', group: 'Copy / Brand', icon: 'chart', height: '1800px' },
  { id: 's19', number: '19', title: 'Privacy & Data Agreement', group: 'Legal', icon: 'file', height: '2600px' },
  { id: 's20', number: '20', title: 'A/B Test Scenarios', group: 'AI / Build', icon: 'compass', height: '2500px' },
  { id: 's21', number: '21', title: 'Tech Stack Cost', group: 'Revenue', icon: 'chart', height: '1800px' },
  { id: 's22', number: '22', title: 'Domain Research', group: 'Copy / Brand', icon: 'sparkles', height: '1800px' },
  { id: 's23', number: '23', title: 'Onboarding & Activation Flow', group: 'GTM', icon: 'book', height: '2400px' },
  { id: 's24', number: '24', title: 'SEO Strategy', group: 'GTM', icon: 'compass', height: '1800px' },
  { id: 's25', number: '25', title: 'Agency Playbook', group: 'GTM', icon: 'book', height: '1700px' },
  { id: 's26', number: '26', title: 'Objection Handling', group: 'GTM', icon: 'book', height: '2600px' },
] as const;

export type BlueprintSection = (typeof blueprintSections)[number];
